<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Personal Details</name>
   <tag></tag>
   <elementGuidId>a0bf2918-37fd-4e2f-a668-8e28846aa31d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>67b88c6f-302d-4ba5-b3b7-293252ef94b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>798f5282-1528-4e49-bb74-feac2b06210b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-gswNZR bbLVwL account-setting-tab tab-active</value>
      <webElementGuid>64a17b94-61a6-487f-b494-82b0435b5090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personal Details</value>
      <webElementGuid>8cb8e834-b131-4494-a200-b87badff0f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-account-setting&quot;]/ul[@class=&quot;sc-bcXHqe sZiLj account-setting-header&quot;]/li[@id=&quot;0&quot;]</value>
      <webElementGuid>a1c95ef6-4ffc-4747-8679-0ac26e5a1199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='0']</value>
      <webElementGuid>6e8e3d76-e519-4cd4-9259-c8f39f7a3c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div[2]/div/ul/li</value>
      <webElementGuid>8df17fab-dc3f-4d22-92b8-9e56ef064998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Setting'])[1]/following::li[1]</value>
      <webElementGuid>93ae396f-6c52-4c22-a494-324620db7045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[3]/following::li[1]</value>
      <webElementGuid>848889f1-ec75-4fe7-baca-e3713701eb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[3]/preceding::li[4]</value>
      <webElementGuid>8ebc8820-2cc6-4b56-83f4-43b73363397f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eklipse now support Rumble.com'])[1]/preceding::li[4]</value>
      <webElementGuid>fff9f609-6cd7-4317-8f81-d20f3adc4969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li</value>
      <webElementGuid>097dfd63-0511-4706-a6e4-63670dd42b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '0' and (text() = 'Personal Details' or . = 'Personal Details')]</value>
      <webElementGuid>0a15d2e8-f003-4955-8ea8-32b48a3829c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
