<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Features_logo-desktop</name>
   <tag></tag>
   <elementGuidId>1c885642-7ff4-40e8-ac63-c8cd9d3dea2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Eklipse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo-desktop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ef8021b-057e-4739-a1a7-483b11ade507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-desktop</value>
      <webElementGuid>e2aa655d-0ee7-49ef-8b01-761e2407b59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/09/logo_white.png?fit=251%2C50&amp;ssl=1</value>
      <webElementGuid>27270f30-d089-4c91-9f02-7ad1fbf6460b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Eklipse</value>
      <webElementGuid>751a8c85-0fa2-4077-8a33-7f6da21826c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;page-template-default page page-id-15653 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-15653 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--left&quot;]/div[@class=&quot;header-main__logo&quot;]/a[1]/img[@class=&quot;logo-desktop&quot;]</value>
      <webElementGuid>18c2280a-05bd-466f-b92b-5d61372631c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Eklipse']</value>
      <webElementGuid>66c38ae6-7083-4211-ae07-bb9b7a62cca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4dbff39b-6c43-41e5-80bd-10691b10741b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/09/logo_white.png?fit=251%2C50&amp;ssl=1' and @alt = 'Eklipse']</value>
      <webElementGuid>dafd4375-c192-4f97-b5b5-e3abb80086b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
